### ISSUE TITLE
`<h1>` 문자열 수정

### ISSUE THREAD

**Issue by hemoptysisheart** [hemoptysisheart/marusei#8]
https://github.com/hemoptysisheart/marusei/blob/ed074b57baee6a69f5ab48d851e797cfaa583ef4/front/templates/page/login.html#L15

로그인 페이지의 `<h1>`의 문자열 수정.

예) `회원가입` 삭제.

**Comment by dajeongChoi** [comment]
https://github.com/hemoptysisheart/marusei/pull/10
Issue#8  수정 풀리퀘입니다.
