### ISSUE TITLE
`"action"` 수정.

### ISSUE THREAD

**Issue by hemoptysisheart** [hemoptysisheart/marusei#9]
https://github.com/hemoptysisheart/marusei/blob/ed074b57baee6a69f5ab48d851e797cfaa583ef4/front/templates/page/login.html#L16

폼 서브밋 => 파일 없음.

**Comment by dajeongChoi** [comment]
https://github.com/hemoptysisheart/marusei/pull/10
Issue#9  수정 풀리퀘입니다.
